# Generated by Django 5.1.4 on 2025-01-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='codigo_qr',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='empresa.propietario'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Conejo', 'Conejo')], max_length=50, null=True),
        ),
    ]
