# Generated by Django 5.1.4 on 2026-06-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_placaqr_remove_mascota_codigo_qr_mascota_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='mostrar_contacto_publico',
            field=models.BooleanField(default=True, verbose_name='Mostrar datos de contacto al público'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
