# Generated by Django 5.1.4 on 2026-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_reportemascotaencontrada_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='observaciones_cierre',
            field=models.TextField(blank=True, help_text='Notas del administrador sobre lo ocurrido con el reporte.', null=True),
        ),
        migrations.AddField(
            model_name='reportemascotaencontrada',
            name='resultado_reporte',
            field=models.CharField(choices=[('Sin definir', 'Sin definir'), ('Mascota encontrada', 'Mascota encontrada'), ('Falsa alarma', 'Falsa alarma'), ('Reporte duplicado', 'Reporte duplicado'), ('No localizada', 'No localizada'), ('Otro', 'Otro')], default='Sin definir', max_length=40),
        ),
    ]
